# action.yml
name: "mongo-action"
author: "Evan Tay"
description: "A Github Action that creates a Docker container using the official mongo image."
branding:
  icon: "database"
  color: "green"
inputs:
  image_version:
    description: "The mongo Docker image version to use"
    required: false
    default: "latest"
  port:
    description: "The port where the mongo service will be published at" 
    required: false
    default: 27017
runs:
  using: "node16"
  main: "dist/index.js"
